### ISSUE TITLE
403 on swagger endpoint

### ISSUE THREAD

**Issue by Big-Gray-Al** [CommonsBuild/praise_backend#19]
On following this README instructions, I get a 403: unauthorized when trying to access
http://localhost:8088/swagger-ui

This is on both main and dev branches from both firefox and chromium.

I saw kristopher accessing it the other day so Im sure that I just need to adjust a configuration somewhere.  

Please let me know what I need to do to get access.

Many thanks

**Comment by kristoferlund** [comment]
Add .html to the url.

http://localhost:8088/swagger-ui.html

**Comment by Big-Gray-Al** [comment]
Confirmed on this.
